stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw
    outs:
    - data/preprocessed/hour_clean.csv
  split:
    cmd: python src/split.py
    deps:
    - data/preprocessed/hour_clean.csv
    - src/preprocess.py
    params:
    - split.ratio
    outs:
    - data/preprocessed/test.csv
    - data/preprocessed/train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/preprocessed/test.csv
    - data/preprocessed/train.csv
    outs:
    - model/catboost.pickle
    metrics:
    - evaluation/metrics.json:
        cache: false