stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw
    - src/config/config_path.py
    outs:
    - data/preprocessed/hour.parquet
  train:
    cmd: python src/train.py
    deps:
    - data/preprocessed/hour.parquet
    - src/config/config_path.py
    params:
    - split.ratio
    outs:
    - model/catboost.pickle
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/preprocessed/hour.parquet
    - model/catboost.pickle
    metrics:
    - evaluation/metrics.json:
        cache: false
