stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw
    outs:
    - data/preprocessed
  split:
    cmd: python src/split.py
    deps:
    - data/preprocessed
    - src/preprocess.py
    params:
    - split.ratio
    outs:
    - data/test
    - data/train
    - model
  train:
    cmd: python src/train.py
    deps:
    - data/test
    - data/train
    metrics:
    - evaluation/metrics.json:
        cache: false
