PATHS:
  raw_data: data/raw/hour.csv
  preprocessed_data: data/preprocessed/hour_clean.csv
  train: data/preprocessed/train.csv
  test: data/preprocessed/test.csv
  
cb_features:
  target: 'cnt'
  feature_names: ['season', 'yr', 'mnth', 'hr', 'holiday', 'weekday', 'workingday', 'weathersit', 'temp', 'hum', 'windspeed']

split:
  ratio: 0.2